### ISSUE TITLE
Validate the shacl schema in node.js

### ISSUE THREAD

**Issue by LoznianuAnamaria** [oceanprotocol/ocean-node#19]
Indexer should support multiple types of DDO schemas.  Can be Ocean related, Gaia-x related, custom ones, etc

As a reference, Aquarius supports only the last version of Ocean DDO (https://github.com/oceanprotocol/aquarius/tree/main/aquarius/ddo_checker/shacl_schemas/v4)

To Do:  implement a class that deals with multiple schemas

- [ ]  have a folder that contains two file per schema definition and load list of schemas
- [ ]  on startup, create collection, mappings, etc if they do not exists
- [ ]  expose validateDDO function (ddo)
- [ ]  return collection name for a ddo 
- [ ]  expose list of valid schemas and their body to upper layers
