### ISSUE TITLE
C2D.2: Execution layer Docker API

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#424]
For start, we need the following functionality:

- [x] define how auth works 
- [x] low level function to create volumes
- [x] low level function to create pods
- [x] low level function to get pods status
- [x] low level function to delete volumes

After we have the class, we will integrate it up the stack
