### ISSUE TITLE
Command: downloadFile

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/ocean-node#77]
This will allow users to download a file, after the payment was done.

- [ ]  implement core function download
- [ ]  expose it on http interface
- [ ]  expose it on p2p interface

Command description:

{
  command: "download",
  node: "NodeB ID",  // optional, if missing, it refers to current node
  documentId,
  serviceId,
  transferTxId,
  fileIndex,
  nonce,
  consumerAddress,
  signature.
 }
Inputs:

 - documentId: String object containing document id (e.g. a DID)
 - serviceId: String, representing the list of `file` objects that describe each file in the dataset
 - transferTxId: Hex string -- the id of on-chain transaction for payment using datatokens 
 - fileIndex: integer, the index of the file from the files list in the dataset
 - nonce: String object, the nonce (either integer, either UTC timestamp format) required for download request
 - consumerAddress: String object containing consumer's address
 - signature: String object containg user signature (signed message).
     The signature is based on hashing the following string concatenation consisting of:
       documentId + nonce

This a glue of all issues in this epic, because the steps are the following:
 - check nonce & signature
 - check provider fees
 - check order tx
 - decrypt url
 - read file content & stream it
 - check if we need to encrypt it using user's private key
 

By doing this, we are going to replace downloadURL command (which was designed only as a test helper)
