### ISSUE TITLE
Nonce tracking

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#83]
When an user interacts with a node, for some actions, it needs to identify itself.
In order to that, user will send a signed message and a nonce.

User's actions:
   - create a message = String(nonce)
   - sign it
   - when calling ocean-node endpoints that do required auth, add nonce and signature as parameters

Ocean-node will check:
 - user's nonce >  previous stored nonce
 - signer of message matches user's address (consumer parameter)
 
  

Example:
GET /endpoint?param1=x&param2=y&nonce=1&signature=0x123&consumer=0x456

TO DO:
- [x]  implement nonce related function in core db  (getNonce(address) ,setNonce(address,newNonce)
- [x]  create a core function nonce(address), that returns stored nonce for an address  ( 0 if not found)
- [x]  expose nonce command to http
- [x]  expose nonce command to libp2p
- [x]  create a core function:  check_nonce(consumer,nonce,signature) that:
     - checks nonce
     - updates new nonce in db
     - returns true/false (+ error message if needed)
